### PR TITLE
Fix command line option parse for epc (Major restructure)

### PR DESCRIPTION
**Pull request by yuutayamada**
In major restructure branch, --epc option didn't work and this PR fix that problem.

### CODE REVIEW

**Comment by yuutayamada** [comment]
Merged #26 (tcp mode's test) and added epc mode's basic tests.

**Comment by Varriount** [comment]
@araq Care to review?

**Comment by yuutayamada** [comment]
Added Araq's recent commits related loading config.nims in nimsuggest and the test. I think it seems working.

**Comment by yuutayamada** [comment]
Fixed broken TCP's tests (use and chk methods) and modified tests to use `bats` for prettier output. Hope you like it :)
https://travis-ci.org/yuutayamada/nimsuggest/builds/146744151

**Comment by Araq** [comment]
Good but the major restructure branch is obsolete.

**Pull request closed without merging**
